### ISSUE TITLE
normal maps, mdl materials

### ISSUE THREAD

**Issue by PerspectivesLab** [jbikker/lighthouse2#11]
i am leaving my comments here since its not possible to register new users to ompf2 forums
- i have been using lighthouse2 with simple models gltf with normals maps, can you let us know if this is functional in lighthouse2 ?
- would it be possible to implement MDL nvidia materials, are you planning this on your roadmap ?
thx

**Comment by jbikker** [comment]
Normal maps should work properly in Lighthouse 2, although I admit that I have not used the functionality for quite some time. I will verify it next week.

Regarding the roadmap: development is primarily steered by education and student projects, and thus somewhat random. The original aim was to build a framework for real-time path tracing in games. If MDL fits that goal it may get implemented someday, although there are no concrete plans yet.

Today LH2 gained PBRT material support, which obviously does not fit the real-time game goal. The PBRT core should support full material stacks.

**Comment by PerspectivesLab** [comment]
here are the screenshots, the model provided is downloadable here 
[normal_map.zip](https://github.com/jbikker/lighthouse2/files/4052737/normal_map.zip)


the model can be uploaded to https://threejs.org/editor/ ( drag and drop in the editor and add a directional light ) here is a shot of the normal map
![threejs](https://user-images.githubusercontent.com/25195799/72243465-52725500-35ec-11ea-90ea-acd31692749a.jpg)
while loading in lighthouse2
![Untitled-2](https://user-images.githubusercontent.com/25195799/72243486-5c945380-35ec-11ea-9d88-5d7af58e9f76.jpg)
it could be that the map texture is loaded but doesnt get assigned to the material.

regarding MDL materials, ok for pbrt, the mdl approach was also nice because of the material library, and prebuilt materials, so if i want to follow the pbrt V3 specs i would need to follow the reference provided here ( https://www.pbrt.org/fileformat-v3.html#materials ) and implement the file format parser here ( https://github.com/ingowald/pbrt-parser ) is that correct ? 

and last question, how can we set the spp quality for the renderer, for it to render quicker with less ray bouncing/ quality ? thx

**Comment by jbikker** [comment]
The normal map issue has been resolved.
Regarding more complex materials: the pbrt support is quite rudimentary and probably not ready for prime time. Expect more focus on a fast ubershader for real-time rendering, rather than more sophisticated materials.
Regarding spp: yes; in main.cpp of e.g. imguiapp you can change spp from 1 to some other value; this will yield better performance in terms of rays per second.
