### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by Hurleyworks** [jbikker/lighthouse2#16]
No issue. I can't seem to join your forum and I just want to thank you for making this great 
project available and show you a render I've made with it

![Feast](https://user-images.githubusercontent.com/8120255/82126492-283bca00-977b-11ea-85e9-7d98299fd140.png)

And here's how I made it 
https://www.youtube.com/watch?v=bD_oN9cLmeI

**Comment by jbikker** [comment]
That is very cool!
