### ISSUE TITLE
Optix error unsupported ABI version

### ISSUE THREAD

**Issue by straaljager** [jbikker/lighthouse2#3]
Hi Jacco,

I followed the instructions to compile Lighthouse with VS2017, however when running the application it shows a fatal error:

```
running on GPU: GeForce RTX 2060 (30 SMs, 6GB VRAM)

Error at line 124 of c:\users\sam\downloads\lighthouse2-master\lighthouse2-master\lib\rendercore_optix7\rendercore.cpp:
optixInit()
OPTIX_ERROR_UNSUPPORTED_ABI_VERSION (7801)
```

Googling this error seems to point to an issue with Optix 7. Any help on how to resolve it is appreciated.

**Comment by straaljager** [comment]
Updating the Nvidia driver solved this error, however a new fatal error appeared in platform.cpp (I cannot provide more details unfortunately)

**Comment by meirbon** [comment]
@straaljager support for OptiX 7 came with a driver update as you found out. There is a string formatting bug in platform.cpp, that's why you aren't seeing the actual error message. It is most likely because of this function in platform.cpp:

```
void DrawQuad()
{
	static GLuint vao = 0;
	if (!vao)
	{
                ...
		glBindVertexArray( 0 );
->	        glDisableVertexAttribArray( 0 ); // Causes GL_INVALID_OPERATION
->	        glDisableVertexAttribArray( 1 ); // Causes GL_INVALID_OPERATION
	}
	glBindVertexArray( vao );
	glDrawArrays( GL_TRIANGLES, 0, 6 );
	glBindVertexArray( 0 );
}
```

glDisableVertexAttribArray causes a GL_INVALID_OPERATION error as there is no vertex array object bound. It seems this used to not cause any errors with previous drivers.

**Comment by jbikker** [comment]
Hi Sam, hi Meir,
Glad to see you guys here. :)
The glDisableVertexAttribArray commands are still not giving me any issues, but I removed them in the latest revision. I'll assume that this resolved the issue. 
- Jacco.

**Comment by straaljager** [comment]
Thanks, I just tried the latest revision. While the previous error is now gone, a new one popped up unfortunately:

```
cudaGraphicsGLRegisterImage() failed: Operating system error!
c:\users\sam\downloads\lighthouse2-master(2)\lighthouse2-master\lib\cuda\shared_host_code\interoptexture.cpp, line 51

```
Perhaps I should open a new issue?

**Comment by jbikker** [comment]
Are you on a laptop? In that case you may want to force the use of the
NVIDIA device rather than the integrated chip.

- Jacco.

**Comment by straaljager** [comment]
Yes that solved it, thanks!
