### ISSUE TITLE
NaN in PackNormal compression

### ISSUE THREAD

**Issue by RobbinMarcus** [jbikker/lighthouse2#4]
Hi Jacco, 

The function
```
// from: https://aras-p.info/texts/CompactNormalStorage.html
LH2_DEVFUNC uint PackNormal( float3 N )
{
#if 1
	// more efficient
	const float f = 65535.0f / sqrtf( 8.0f * N.z + 8.0f );
	return (uint)(N.x * f + 32767.0f) + ((uint)(N.y * f + 32767.0f) << 16);
#else
	float2 enc = normalize( make_float2( N ) ) * (sqrtf( -N.z * 0.5f + 0.5f ));
	enc = enc * 0.5f + 0.5f;
	return (uint)(enc.x * 65535.0f) + ((uint)(enc.y * 65535.0f) << 16);
#endif
}
```

Produces a NaN for input normal `(0, 0, -1)` which leads to a return value of 0. 
Unpacking the 0 value leads to a NaN normal. 

I solved the problem I had by adding a max check with an Epsilon of 0.0001f:

```
const float f = 65535.0f / fmaxf(sqrtf(8.0f * normal.z + 8.0f), 0.0001f);
```

I was running this code on CPU, so I'm unsure if this is handled differently on the GPU.

**Comment by jbikker** [comment]
Thanks for reporting that! This affects the MIS calculations in all path tracers, since that relies on the normal for the previous vertex which is stored in a packed format. So I will just say thank you and drop in your fix in my code.
