### ISSUE TITLE
Project not building Debug x64

### ISSUE THREAD

**Issue by jan-van-bergen** [jbikker/lighthouse2#5]
If I try to build the project for the Debug x64 target I get error C2855: command-line option '/Z7' inconsistent with precompiled header. 
In Release x64 mode I don't get this error and it builds fine.

The issue seems to be caused by the latest commit (e0ed8c3). If I go back to any previous commit it does build.

**Comment by jbikker** [comment]
Yes, sorry about that. The latest revision should compile fine for both debug and release.
